[2023-04-04T04:00:25.181+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:00:19.828558+00:00 [queued]>
[2023-04-04T04:00:25.186+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:00:19.828558+00:00 [queued]>
[2023-04-04T04:00:25.187+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T04:00:25.187+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-04T04:00:25.188+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T04:00:25.196+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_azure_sql> on 2023-04-04 04:00:19.828558+00:00
[2023-04-04T04:00:25.200+0000] {standard_task_runner.py:55} INFO - Started process 586 to run task
[2023-04-04T04:00:25.204+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag2', 'upload_to_azure_sql', 'manual__2023-04-04T04:00:19.828558+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/test_dag2.py', '--cfg-path', '/tmp/tmpq1bp6k2j']
[2023-04-04T04:00:25.204+0000] {standard_task_runner.py:83} INFO - Job 478: Subtask upload_to_azure_sql
[2023-04-04T04:00:25.272+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:00:19.828558+00:00 [running]> on host 8206d31aa2d9
[2023-04-04T04:00:25.328+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag2
AIRFLOW_CTX_TASK_ID=upload_to_azure_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T04:00:19.828558+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T04:00:19.828558+00:00
[2023-04-04T04:00:26.584+0000] {logging_mixin.py:137} INFO - I AM HEREEEEEEEEEEEEE
[2023-04-04T04:00:26.678+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag2.py", line 149, in upload_to_azure_sql
    row.scores_away_total)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]String or binary data would be truncated in table 'cs779.dbo.basketball_games', column 'date'. Truncated value: '2'. (2628) (SQLExecDirectW)")
[2023-04-04T04:00:26.708+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag2, task_id=upload_to_azure_sql, execution_date=20230404T040019, start_date=20230404T040025, end_date=20230404T040026
[2023-04-04T04:00:26.723+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 478 for task upload_to_azure_sql (('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]String or binary data would be truncated in table 'cs779.dbo.basketball_games', column 'date'. Truncated value: '2'. (2628) (SQLExecDirectW)"); 586)
[2023-04-04T04:00:26.786+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-04T04:00:26.813+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
